import { MaterialIcons } from "@expo/vector-icons";

const iconMapping: Record<string, keyof typeof MaterialIcons.glyphMap> = {
  // Interface & Display icons
  text: "text-fields",
  input: "input",
  code: "code",
  hash: "tag",
  calendar_day: "calendar-today",
  access_time: "access-time",
  checkbox: "check-box",
  radio_button: "radio-button-checked",
  toggle: "toggle-on",
  dropdown: "arrow-drop-down",
  image: "image",
  file: "insert-drive-file",
  location: "place",
  map: "map",
  color: "color-lens",
  slider: "tune",
  sort: "sort",
  filter_list: "filter-list",

  // Navigation & UI icons
  menu: "menu",
  search: "search",
  add: "add",
  edit: "edit",
  delete: "delete",
  archive: "archive",
  folder: "folder",
  visibility: "visibility",
  visibility_off: "visibility-off",
  more_vert: "more-vert",
  more_horiz: "more-horiz",
  refresh: "refresh",
  close: "close",
  check: "check",
  settings: "settings",
  help: "help",
  info: "info",
  warning: "warning",
  error: "error",
  person: "person",
  group: "group",
  bookmark: "bookmark",
  star: "star",
  heart: "favorite",
  link: "link",
  send: "send",
  share: "share",
  download: "download",
  upload: "upload",
  cloud: "cloud",
  sync: "sync",
  print: "print",
  home: "home",
  list: "list",
  grid: "grid-view",
  table: "table-view",
};

export default iconMapping;
