// Field Types (from Directus Schema)
export type DirectusFieldType =
  | "alias"
  | "binary"
  | "boolean"
  | "date"
  | "dateTime"
  | "decimal"
  | "float"
  | "geometry"
  | "hash"
  | "integer"
  | "json"
  | "string"
  | "text"
  | "time"
  | "timestamp"
  | "uuid"
  | "default";

// Field Interfaces (from Directus)
export type DirectusFieldInterface =
  | "boolean"
  | "button-group"
  | "calendar"
  | "checkboxes"
  | "code"
  | "color"
  | "datetime"
  | "display"
  | "divider"
  | "dropdown"
  | "file"
  | "files"
  | "group"
  | "icon"
  | "image"
  | "input"
  | "input-block"
  | "input-hash"
  | "input-multiline"
  | "input-rich-text-html"
  | "input-rich-text-md"
  | "list"
  | "map"
  | "notice"
  | "presentation"
  | "radio-buttons"
  | "repeater"
  | "select-color"
  | "select-dropdown"
  | "select-multiple"
  | "slider"
  | "tags"
  | "textarea"
  | "time"
  | "toggle";
